### ISSUE TITLE
I suddenly don't exist.

### ISSUE THREAD

**Issue by wopian** [fuzetsu/hummingbird-user-compare#2]
![](http://i.imgur.com/hXV8AYA.png).

https://hummingbird.me/users/wopian

All of the user APIs work fine on my account.

**Comment by fuzetsu** [comment]
That's strange, the php script is requesting this URL `https://hummingbird.me/library_entries?user_id=wopian` for your username, when I try it directly in my browser I'm getting a `502`. It works fine for other users though. Is your library working properly on the main site? or has hummingbird changed their underlying API.

![image](https://cloud.githubusercontent.com/assets/848652/11305163/513529ce-8f79-11e5-9f9c-dff739177c8b.png)

**Comment by kufii** [comment]
I noticed that the API call only works if you explicitly state a status (for example https://hummingbird.me/library_entries?user_id=wopian&status=Currently+Watching). I also noticed that the status tabs aren't loading on your library. This seems to be only happening for you and is definitely an issue on hummingbirds end

**Comment by wopian** [comment]
Ah that timeout bug for large libraries is still a thing. Never mind then :)
